version: '3'

services:
  app:
    build: ./docker/node
    command: ["npm", "start"]
    networks: 
      - backend
    volumes:
      - ./:/app
    networks:
      - backend

networks:
  backend: {}
